version: "3.9"
services:
  eureka:
    image: eureka
    ports:
      - "8761:8761"
    environment:
      eureka.instance.hostname: eureka
  student:
    image: student
    ports:
      - "8081:8081"
    environment:
      eureka.client.serviceUrl.defaultZone: http://eureka:8761/eureka/
  teacher:
    image: teacher
    ports:
      - "8082:8082"
    environment:
      eureka.client.serviceUrl.defaultZone: http://eureka:8761/eureka/
  