version: "3.9"
services:
  eureka:
    image: eureka
    ports:
      - "8761:8761"
    environment:
      eureka.instance.hostname: eureka
  student:
    image: student
    ports:
      - "8081:8081"
    depends_on:
      - eureka
    environment:
      eureka.client.serviceUrl.defaultZone: http://eureka:8761/eureka/
  